import asyncio
from api_clients import get_meta_llama_soap

def read_conversation_from_file(file_path: str) -> str:
    """Reads the conversation text from a .txt file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return ""
    except Exception as e:
        print(f"Error reading file: {str(e)}")
        return ""

async def test_meta_llama(file_path: str):
    """Tests the Meta Llama API using the provided conversation file."""
    conversation = read_conversation_from_file(file_path)
    if not conversation:
        print("No conversation content to process.")
        return

    print("Testing Meta Llama API...")
    soap_note = await get_meta_llama_soap(conversation)

    if not soap_note:
        print("No SOAP note was generated by Meta Llama.")
        return

    print("\nGenerated SOAP Note by Meta Llama:")
    print("-" * 80)
    print(soap_note)
    print("-" * 80)

if __name__ == "__main__":
    conversation_file_path = "conversations/CAR0004.txt"
    asyncio.run(test_meta_llama(conversation_file_path))
